apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
  namespace: dummy-test
  labels:
    app: foobar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      labels:
        app: foobar
    spec:
      containers:
        - name: foobar
          image: nginx:1.25
          ports:
            - containerPort: 80
